#include "molecule.h"

#include <fmt/format.h>

#include "atom.h"
#include "defines.h"
#include "string_tools.h"

Molecule::Molecule(int _mol_id) : id(_mol_id) {};

Molecule::~Molecule() {
    mol_atoms.clear();
    mol_bonds.clear();
}

std::string Molecule::info() {
    if ((mol_atoms.size() > 0) && (formula.empty())) update_formula();

    std::string s = fmt::format("Mol: {} Atoms:{} Bonds:{}\n", formula, mol_atoms.size(), mol_bonds.size());

    return s;
}

void Molecule::insert(Atom *&atom) {
    if (!this->has(atom)) {
        mol_atoms.push_back(atom);
        atom_ids.insert(atom->id);
    }
}

void Molecule::insert(Bond *&bond) {
    if (!this->has(bond)) mol_bonds.push_back(bond);
}

bool Molecule::has(Atom *&atom) {
    for (auto &exist : mol_atoms) {
        if (atom == exist) return true;
    }
    return false;
}

bool Molecule::has(Bond *&bond) {
    for (auto &exist : mol_bonds) {
        if (bond == exist) return true;
    }
    return false;
}

void Molecule::update_formula() {
    std::string tmp_formula;

    for (auto &mol_atom : mol_atoms) {
        types_nums[mol_atom->type_name]++;  // If key of map not exist, create
                                            // key-value and value++, If exists,
                                            // value++.
    }

    for (auto &pair : types_nums) {
        tmp_formula += fmt::format("{}{}", pair.first, pair.second);
    }

    formula = rename_formula(tmp_formula);
}

void Molecule::calc_bond_order() {
    // Get initial valence electrons for each atom.
    for (auto &atom : mol_atoms) {
        if (default_atom_valence_electrons.find(atom->type_name) != default_atom_valence_electrons.end()) {
            atom->valence_electrons = default_atom_valence_electrons[atom->type_name];
        } else {
            atom->valence_electrons = 8;
        }

        if (atom->valence_electrons == 8) {
            atom->valence_electrons_saturated = true;
        }
    }

    // Continue building bonds until no more can be added, atoms have 8 valence electrons considered as saturated.
    bool bonds_created = true;
    while (bonds_created) {
        bonds_created = false;
        for (auto &bond : mol_bonds) {
            if (!bond->atom_i->valence_electrons_saturated && !bond->atom_j->valence_electrons_saturated) {
                bond->order++;
                bond->atom_i->valence_electrons++;
                bond->atom_j->valence_electrons++;
                bonds_created = true;

                if (bond->atom_i->valence_electrons >= 8) {
                    bond->atom_i->valence_electrons_saturated = true;
                }
                if (bond->atom_j->valence_electrons >= 8) {
                    bond->atom_j->valence_electrons_saturated = true;
                }
            }
        }
    }
}

void Molecule::dump_mol2(const std::string &filepath) {
    FILE *fp = fopen(filepath.c_str(), "w");
    fmt::print(fp, "@<TRIPOS>MOLECULE\n");
    fmt::print(fp, "Generated by ReaxTools\n");
    fmt::print(fp, "{} {} {}\n", formula, mol_atoms.size(), mol_bonds.size());
    fmt::print(fp, "@<TRIPOS>ATOM\n");

    for (int i = 0; i < mol_atoms.size(); i++) {
        fmt::print(fp, "{} {} {} {} {} {}\n", i + 1, mol_atoms[i]->type_name, mol_atoms[i]->coord[0],
                   mol_atoms[i]->coord[1], mol_atoms[i]->coord[2], mol_atoms[i]->type_name);
    }

    int tmp_bond_order = 0;
    fmt::print(fp, "@<TRIPOS>BOND\n");
    for (int i = 0; i < mol_bonds.size(); i++) {
        if (mol_bonds[i]->order <= 1) {
            fmt::print(fp, "{} {} {} 1\n", i + 1, mol_bonds[i]->atom_i->id, mol_bonds[i]->atom_j->id);
        } else {
            fmt::print(fp, "{} {} {} {}\n", i + 1, mol_bonds[i]->atom_i->id, mol_bonds[i]->atom_j->id,
                       mol_bonds[i]->order);
        }
    }
    fclose(fp);
}

// VERY IMPORTANT: change later: compare by topology, not by formula.
bool operator==(const Molecule &lhs, const Molecule &rhs) { return lhs.formula == rhs.formula; }

// VERY IMPORTANT: change later: compare by topology, not by formula.
bool operator!=(const Molecule &lhs, const Molecule &rhs) { return !(lhs == rhs); }
