#include "reax_flow.h"

#include <algorithm>
#include <fstream>
#include <iostream>
#include <mutex>

#include "fmt/format.h"
#include "universe.h"

// Generated by Claude-3.7
void ReaxFlow::add_reaction(int frame, Molecule *source, Molecule *target) {
    // already locked in upper calling.

    // Get or create source node
    int source_id = -1;
    if (formula_to_node_id.find(source->formula) != formula_to_node_id.end()) {
        source_id = formula_to_node_id[source->formula];
        // Update node appearance frames
        if (std::find(nodes[source_id]->frames_appeared.begin(), nodes[source_id]->frames_appeared.end(), frame - 1) ==
            nodes[source_id]->frames_appeared.end()) {
            nodes[source_id]->frames_appeared.push_back(frame - 1);
        }
    } else {
        // Create new node
        // TODO: Generate SMILES string
        Node *source_node = new Node();  // Allocate memory for the new node
        source_node->formula = source->formula;
        source_node->smiles = "";
        source_node->frames_appeared.push_back(frame - 1);

        nodes.push_back(source_node);
        source_id = nodes.size() - 1;
        formula_to_node_id[source->formula] = source_id;
    }

    // Get or create target node
    int target_id = -1;
    if (formula_to_node_id.find(target->formula) != formula_to_node_id.end()) {
        target_id = formula_to_node_id[target->formula];
        // Update node appearance frames
        if (std::find(nodes[target_id]->frames_appeared.begin(), nodes[target_id]->frames_appeared.end(), frame) ==
            nodes[target_id]->frames_appeared.end()) {
            nodes[target_id]->frames_appeared.push_back(frame);
        }
    } else {
        // Create new node
        Node *target_node = new Node();  // Allocate memory for the new node
        target_node->formula = target->formula;
        target_node->smiles = "";
        target_node->frames_appeared.push_back(frame);

        nodes.push_back(target_node);
        target_id = nodes.size() - 1;
        formula_to_node_id[target->formula] = target_id;
    }

    // Check if the edge already exists
    bool edge_exists = false;
    for (auto &edge : edges) {
        if (edge->source_node_id == source_id && edge->target_node_id == target_id) {
            // Edge already exists, increase reaction count
            edge->reaction_count++;
            edge->frames_occurred.push_back(frame);
            edge_exists = true;
            break;
        }
    }

    // If the edge does not exist, create a new edge
    if (!edge_exists) {
        Edge *new_edge = new Edge();  // Allocate memory for the new edge
        new_edge->source_node_id = source_id;
        new_edge->target_node_id = target_id;
        new_edge->reaction_count = 1;
        new_edge->frames_occurred.push_back(frame);
        edges.push_back(new_edge);
    }
}

// Generate reaction flow report
void ReaxFlow::brief_report() {
    std::cout << "=== Reaction Flow Report ===" << std::endl;
    std::cout << "Total nodes (species): " << nodes.size() << std::endl;
    std::cout << "Total edges (reactions): " << edges.size() << std::endl;

    // Sort edges by reaction count
    std::vector<std::pair<int, int>> sorted_edges;
    for (size_t i = 0; i < edges.size(); i++) {
        sorted_edges.push_back({i, edges[i]->reaction_count});
    }

    std::sort(sorted_edges.begin(), sorted_edges.end(),
              [](const auto &a, const auto &b) { return a.second > b.second; });

    // Display the top 10 most frequent reactions
    std::cout << "\nTop reactions:" << std::endl;
    int count = 0;
    for (const auto &pair : sorted_edges) {
        if (count >= 10) break;

        const Edge *edge = edges[pair.first];
        std::cout << fmt::format("{}: {} -> {} (count: {})", count + 1, nodes[edge->source_node_id]->formula,
                                 nodes[edge->target_node_id]->formula, pair.second)
                  << std::endl;
        count++;
    }
}

// Save reaction flow graph as DOT format for Graphviz.
void ReaxFlow::save_graph(const std::string &raw_file_path, int &max_reactions) {
    std::string save_path = raw_file_path.substr(0, raw_file_path.find_last_of(".")) + ".dot";
    std::ofstream file(save_path);

    if (!file) {
        std::cerr << "Error: Could not open dot file {} for writing.";
        return;
    }

    // Sort edges by reaction count in descending order
    std::vector<Edge *> sorted_edges = edges;
    std::sort(sorted_edges.begin(), sorted_edges.end(),
              [](const Edge *a, const Edge *b) { return a->reaction_count > b->reaction_count; });

    int reaction_count_threshold;

    if (sorted_edges.size() < max_reactions) {
        reaction_count_threshold = 0;
    } else {
        reaction_count_threshold = sorted_edges[max_reactions - 1]->reaction_count;
    }

    std::vector<Edge *> output_edges;
    std::vector<Node *> output_nodes;
    std::map<int, int> node_id_map;  // Map from original node id to new node id

    for (auto &edge : edges) {
        if (edge->reaction_count < reaction_count_threshold) continue;

        // Add source node if not already added
        if (node_id_map.find(edge->source_node_id) == node_id_map.end()) {
            output_nodes.push_back(nodes[edge->source_node_id]);
            node_id_map[edge->source_node_id] = output_nodes.size() - 1;
        }

        // Add target node if not already added
        if (node_id_map.find(edge->target_node_id) == node_id_map.end()) {
            output_nodes.push_back(nodes[edge->target_node_id]);
            node_id_map[edge->target_node_id] = output_nodes.size() - 1;
        }

        // Add edge to output edges
        output_edges.push_back(edge);
    }

    // DOT file header
    file << "digraph ReactionFlow {\n";
    file << "  rankdir=LR;\n";
    file << "  node [shape=box, style=filled, fillcolor=lightblue];\n\n";

    // Write nodes
    for (size_t i = 0; i < output_nodes.size(); i++) {
        file << "  node" << i << " [label=\"" << output_nodes[i]->formula << "\"];\n";
    }

    file << "\n";

    // Write edges
    float penwidth = 1.0f;
    for (const auto &edge : output_edges) {
        penwidth = std::min(5.0, 1.0 + log(edge->reaction_count));
        file << " node" << node_id_map[edge->source_node_id] << " -> node" << node_id_map[edge->target_node_id]
             << " [label=\"" << edge->reaction_count << "\", penwidth=" << penwidth << "];\n";
    }

    file << "}\n";
    file.close();

    fmt::print("Reaction flow graph saved to {}\n", save_path);
}
